#!/bin/sh
#
# Copyright 2022-2026, Marc S. Brooks (https://mbrooks.info)
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license.php

### BEGIN INIT INFO
# Provides:          game-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Steam powered Windows game server
# Description:       Provides commands to manage your game instance.
### END INIT INFO

. /lib/lsb/init-functions
. /var/run/docker-env

SCRIPT=`basename $0`
BASEDIR=/usr/games
PROGDIR=$BASEDIR/.wine/drive_c/Program\ Files\ \(x86\)
GAMEDIR=$PROGDIR/Steam/steamapps/common
USER=games

[ "$HEADLESS" = "yes" ] && DAEMON=/usr/bin/wineconsole || DAEMON=/usr/bin/wine
test -x $DAEMON || exit 0

# Suppress non-blocking warnings.
export WINEDEBUG=-all

start() {

  # Check for game updates
  update

  log_daemon_msg "Starting game instance" "$DAEMON"
  start-stop-daemon --start --quiet --background --chuid $USER --exec $DAEMON -- "$GAMEDIR"/*/$RUNCMD
  log_end_msg $?
}

stop() {
  log_daemon_msg "Stopping game instance" "$DAEMON"
  start-stop-daemon --stop --quiet --user $USER --oknodo --retry 5
  log_end_msg $?
}

update() {
  log_daemon_msg "Updating game instance" "$DAEMON"
  $DAEMON "$PROGDIR"/Steam/steamcmd.exe +login "$USERNAME" "$PASSWORD" "$GUARDCODE" +app_update "$APPID" +quit 2> /dev/null
  chown -R $USER "$GAMEDIR"
  log_end_msg $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  update)
    stop
    update
    start
    ;;
  *)

  log_failure_msg "Usage: $SCRIPT {start|stop|restart|update}"
  exit 1
esac

exit 0
